<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>New Order</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.5.0/css/bulma.min.css">
  </head>
  <style>
    body{
      font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
      font-size: 14px;
      line-height: 1.42857143;
      color: #333;
    }
    .hero.is-danger {
      background-color: #dd4b39;
      color: #fff;
    }
  </style>
  <body>
  <section class="hero is-danger">
    <div class="hero-body">
      <div class="container">
        <h1 class="title has-text-centered">
          Push Selling System
        </h1>
      </div>
    </div>
  </section>
  <section class="section">
    @yield('content')
  </section>
  <footer class="footer">
    <div class="container">
      <div class="content has-text-centered">
        <p>
          <i>This email generated by Our System, do not reply to this email.</i>
        </p>
        <p>
          <strong>Copyright &copy; {{date('Y')}} <a href="https://magnificom-id.com">Magnificom</a>.</strong> All rights
          reserved.
        </p>
      </div>
    </div>
  </footer>
  </body>
</html>
